# Generated by Django 4.2.4 on 2023-09-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_evento_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='local',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
